version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: 134145
      MYSQL_DATABASE: room_management
      MYSQL_USER: root
    ports:
      - "3306:3306"